### ISSUE TITLE
node_pool_defaults block count changed without having it specified during apply

### ISSUE THREAD

**Issue by davidgrundstrom** [hashicorp/terraform-provider-google#12549]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
Terraform v1.2.9

- provider: registry.terraform.io/hashicorp/google-beta v4.36.0
- provider: registry.terraform.io/hashicorp/google v4.36.0
- provider: registry.terraform.io/hashicorp/random v3.4.3

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
terraform {
  required_version = ">= 0.13"
}

provider "google" {
  region = "europe-west1"
}

resource "google_service_account" "example_sa" {
  project      = google_project.platform_project.project_id
  account_id   = "example-sa"
  display_name = "Service Account"
}

resource "google_container_cluster" "example_cluster" {
  provider    			= google-beta
  name        			= "example"
  location    			= "europe-west1"
  remove_default_node_pool 	= true
  initial_node_count 		= 1
}

resource "google_container_node_pool" "example_node_pool" {
  name                = "example-node-pool"
  location            = "europe-west1"
  cluster             = google_container_cluster.example_cluster.name
  initial_node_count  = 1

  autoscaling {
    max_node_count = 2
    min_node_count = 1
  }

  node_config {
    preemptible     = false
    machine_type    = "n2d-standard-8"
    service_account = google_service_account.example_sa.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }
}
```

### Debug Output
```
Error: Provider produced inconsistent final plan

When expanding the plan for google_container_cluster.example to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/google-beta" produced an invalid new value
for .node_pool_defaults: block count changed from 0 to 1.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Expected Behavior

Terraform Apply succeeding in creating new resources

### Actual Behavior

Terraform fails due to `node_pool_defaults` block count changing value. This is not something we've specified on our cluster and thus I think shouldn't affect our applies.

### Steps to Reproduce

This has happened a few times starting today and is always solved by simply running apply again, I'm not able to actively reproduce it.

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@davidgrundstrom could you share your debug log?

**Comment by philip-harvey** [comment]
Basically the same issue as https://github.com/hashicorp/terraform-provider-google/issues/12422
The newer providers are broken and needs to be fixed.
As a work around you can manually set this with a dynamic block, which is a PITA.

**Comment by davidgrundstrom** [comment]
Skipping adding a debug-log as this was reproduced by @shuyama1 and a potential fix seems to be on the way.

@philip-harvey thank you, will look into introducing this in our state until fix is deployed!

**Comment by thameezb** [comment]
Would it be possible to trigger a release to enable this fix to be pulled in by users?

**Comment by thameezb** [comment]
4.38.0 has been released, and the issue still persists on both `node_pool_defaults` and `node_pool_auto_config`. This has not been resolved

Apply output:
```

│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.cluster.google_container_cluster.cluster to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/google-beta" produced an invalid new value for .node_pool_defaults: block count changed from 0 to 1.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.cluster.google_container_cluster.cluster to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/google-beta" produced an invalid new value for .node_pool_auto_config: block count changed from 0 to 1.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by hSATAC** [comment]
I am also having this issue upgraded to 4.38.0

**Comment by shuyama1** [comment]
Thanks everyone for the feedback! I double checked our release plan. It looks like the fix is not released yet and it will be out in v4.39.0 later this afternoon as scheduled. Please try that after v4.39.0 is released and let me know if the error still occurs. Thanks!

**Comment by AtzeDeVries** [comment]
i still have simular issues
```
erraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.management-gke.google_container_cluster.gke will be updated in-place
  ~ resource "google_container_cluster" "gke" {
        id                          = "projects/management-gke-production-9ee5/locations/europe-north1/clusters/management-gke-prd"
        name                        = "management-gke-prd"
        # (28 unchanged attributes hidden)

      - node_pool_defaults {
        }

        # (24 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

with 4.39
