### ISSUE TITLE
Composer TF Destroy -> googleapi: got HTTP response code 404 

### ISSUE THREAD

**Issue by guicane** [hashicorp/terraform-provider-google#16540]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Description
When recreating a composer environment using Terraform the destroy step fails with a HTTP 404 error saying it cannot find the resource. The only difference I can see is that the resource URL contains v1beta1 whereas if I do a gcloud composer describe on the resource the resulting URL does not have that v1beta1 part.

This is a new error as it didn't use to happen. I'm not sure when it started but I'd say in the last 2 to 3 weeks.

### Terraform Version

Terraform v1.5.7

### Affected Resource(s)

google_composer_environment

### Terraform Configuration Files

```tf
module "composer_env" {
  source  = "terraform-google-modules/composer/google//modules/create_environment_v2"
  version = "3.4.0"

  depends_on = [
    google_project_iam_member.shared_vpc_host_gke_permissions_network,
    google_project_iam_member.shared_vpc_host_gke_permissions,
    google_project_iam_member.composer_worker
  ]

  project_id                       = var.project
  network_project_id               = var.host_project
  composer_env_name                = "${var.environment}-${var.name}-composer"
  region                           = var.region
  image_version                    = var.image_version
  composer_service_account         = google_service_account.composer_sa.email
  network                          = var.network_id
  subnetwork                       = var.subnetwork
  pod_ip_allocation_range_name     = var.pods_secondary_range_name
  service_ip_allocation_range_name = var.services_secondary_range_name
  grant_sa_agent_permission        = true
  use_private_environment          = true
  enable_private_endpoint          = true
  environment_size                 = var.environment_size
  env_variables                    = var.env_variables
  tags                             = var.network_tags
  labels                           = var.labels
  pypi_packages                    = var.pypi_packages
  scheduler = {
    cpu        = var.scheduler_cpu
    memory_gb  = var.scheduler_memory_gb
    storage_gb = var.scheduler_storage_gb
    count      = var.scheduler_node_count
  }
  web_server = {
    cpu        = var.web_server_cpu
    memory_gb  = var.web_server_memory_gb
    storage_gb = var.web_server_storage_gb
  }
  worker = {
    cpu        = var.worker_cpu
    memory_gb  = var.worker_memory_gb
    storage_gb = var.worker_storage_gb
    min_count  = var.worker_node_min_count
    max_count  = var.worker_node_max_count
  }
}

```

### Expected Behavior

`terraform apply` should destroy and recreate the resource without errors.

### Actual Behavior

Destroy step fails with the HTTP error 404.

### Steps to Reproduce

1. `terraform apply` the module.
2.  Apply will fail due to composer needing to go to private repository to pull python packages. It should not taint the resource if python packages fail to be installed. (This is described [here](https://github.com/hashicorp/terraform-provider-google/issues/12781#issuecomment-1702958406) )
3. Add `pip.conf` file to `bucket/config/pip/pip.conf`
4. `terraform apply` again.
5. Due to the resource requiring to be redeployed, the `destroy` is triggered and instantly fails with the HTTP 404 error saying it can't find the resource to be destroyed. (I am able to create the resource from scratch and to gcloud describe it successfully).
```html
module.composer_v2.module.composer_env.google_composer_environment.composer_env: Destroying... [id=projects/project_id/locations/europe-west2/environments/composer_name]
╷
│ Error: googleapi: got HTTP response code 404 with body: <!DOCTYPE html>
│ <html lang=en>
│   <meta charset=utf-8>
│   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
│   <title>Error 404 (Not Found)!!1</title>
│   <style>
│     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
│   </style>
│   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
│   <p><b>404.</b> <ins>That’s an error.</ins>
│   <p>The requested URL <code>/v1beta1/projects/project_id/locations/europe-west2/environments/?alt=json&amp;prettyPrint=false</code> was not found on this server.  <ins>That’s all we know.</ins>

```

### References

* #0000

b/312432844

**Comment by edwardmedia** [comment]
@guicane you are using a module, which makes a little difficult.

Are you able to create a resource that can be used to repro the issue? Please share if you can.

Can you share your debug log?

Are you able to reach out its owner to see if they can help?

**Comment by guicane** [comment]
Thanks for the reply!

> @guicane It appears {environment} is missing in below url. It's hard to say where the problem is.
> 
> ```
> /v1beta1/projects/project_id/locations/europe-west2/environments/?alt=json
> ```
> 
> you are using a module, which makes a little difficult.

I'm using the official Google module which I have been using for over a year without issues. So I'm assuming there has been a change to the api or the provider that is causing this issue.

https://github.com/terraform-google-modules/terraform-google-composer/tree/v3.4.0/modules/create_environment_v2

> 
> Are you able to create a resource that can be used to repro the issue? Please share if you can.
> 

I can create composer initially but the resource is never trully successfully deployed due to the python packages issue I linked above which is what is causing me to do another apply to fix that which is causing this error.

>
> Can you share your debug log?
> 
I'll try to get that

>
> Are you able to reach out its owner to see if they can help?
> 
Due to the googleapi error I thought creating a provider level issue would be more likely that someone would understand this issue than the module that is simply using this provider. I guess I can create an issue in that repo too but it seems it doesn't see much movement.
https://github.com/terraform-google-modules/terraform-google-composer/issues

> Please share the details
> 
> ```
> (I am able to create the resource from scratch and to gcloud describe it successfully).
> ```
This meant I am able to use this module to create the environment and am also able to run a `gcloud beta composer environments describe` command against the composer environment successfully.

**Comment by edwardmedia** [comment]
@guicane the [v3.4.0](https://github.com/terraform-google-modules/terraform-google-composer/releases) of module is one year old. Did you say it had been no issue until recently, when? 

Let's get your log to see if that tell us something. 

It would be good if you can a workable config so I can repro.

**Comment by guicane** [comment]
@edwardmedia the module works "fine" as in, it has its limitations (and overcoming these limitations is how I got to this problem), but it does what it does and it sort of woks if the user has access to the internet to retrieve python packages from pypi.org, which isn't my case.

I use terragrunt and attach here the debug log and the vars log. The variables seem ok and everything is where it should be.

I really think something changed at an api level which is causing this issue.

[debug.log](https://github.com/hashicorp/terraform-provider-google/files/13376067/debug.log)
[terragrunt-debug.tfvars.json](https://github.com/hashicorp/terraform-provider-google/files/13376068/terragrunt-debug.tfvars.json)

**Comment by CaliWee** [comment]
@guicane The way I work around this issue is this: First deploy the composer module but do not list any PyPi packages. Then once the composer environment is successfully created, manually add you pip.conf file configuring access to your private repository. Then add the PyPi packages back in the terraform configuration and apply again.

**Comment by drandell** [comment]
This is an issue going all the way back to 2021 (the oldest ref I could find https://github.com/hashicorp/terraform-provider-google/issues/10709) would have thought this would get fixed by now.

**Comment by dzarmola** [comment]
@guicane To be honest I still don't really understand how could the flow that you're describing be really working before, *however*, Composer rolled out an option to provide a precreated GCS bucket when creating an environment (with a `storage_config.bucket`) which should help with your use case (as you can put the pip.conf inside beforehand).

To help with debugging the actual issue listed here (the 404) could you confirm:
1. You are creating an environment with python packages already listed, with the assumption that Terraform will create environment+update it (which we expect to fail). And then you'll reapply after putting pip.conf in the bucket?

My understanding of Terraform would suggest that this flow (in which your _only_ step - that's only internally a create+update) would result in Terraform treating this as an all around failure, and just delete the environment, so I would expect this 404 to be working as intended

2. Could you reproduce this, and before you reapply check (e.g. with gcloud) whether the environment actually still exists and is in "RUNNING" state?

**Comment by guicane** [comment]
Thanks @dzarmola , since the 5.6 provider update it seems specifying the bucket before deploy works as expected! Tried and tested and we can now move on! 

Thanks!
