### ISSUE TITLE
google_monitoring_dashboard: resource always need to be updated.

### ISSUE THREAD

**Issue by yegle** [hashicorp/terraform-provider-google#7242]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

$ tf -v
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/google v3.38.0
+ provider registry.terraform.io/hashicorp/google-beta v3.38.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.0

### Affected Resource(s)

* google_monitoring_dashboard

### Terraform Configuration Files

https://github.com/google/exposure-notifications-verification-server/blob/main/terraform/alerting/monitoring.tf

### Debug Output

https://gist.github.com/yegle/b53023c79512fcb38bc8e8bcea5e9b8e

### Expected Behavior

There should be no resource change.

### Actual Behavior

See the plan result in https://gist.github.com/yegle/b53023c79512fcb38bc8e8bcea5e9b8e

### Steps to Reproduce

1. `terraform apply`

### References

* b/275111934

**Comment by icco** [comment]
An example of what it shows every time.
```
 # module.en-alerting.google_monitoring_dashboard.verification-server will be updated in-place
  ~ resource "google_monitoring_dashboard" "verification-server" {
      ~ dashboard_json = jsonencode(
          ~ {
                displayName = "Verification Server"
              - etag        = "6a20213c86f6c6c70a72060cfd338c72" -> null
              ~ gridLayout  = {
                  ~ columns = "2" -> 2
                    widgets = [
                        {
                            title   = "Cloud Run Revision - Request Count (grouped) [SUM]"
                            xyChart = {
                                chartOptions = {
                                    mode = "COLOR"
                                }
                                dataSets     = [
                                    {
                                        plotType        = "LINE"
                                        timeSeriesQuery = {
                                            timeSeriesQueryLanguage = <<~EOT
                                                cloud_run_revision :: run.googleapis.com/request_count | align rate() | every 1m | [resource.service_name, metric.response_code_class]
                                            EOT
                                        }
                                    },
                                ]
                            }
                        },
                        {
                            title   = "OpenCensus/en-verification-server/api/issue/attempt_count by label.job [SUM]"
                            xyChart = {
                                chartOptions = {
                                    mode = "COLOR"
                                }
                                dataSets     = [
                                    {
                                        plotType        = "LINE"
                                        timeSeriesQuery = {
                                            timeSeriesQueryLanguage = <<~EOT
                                                generic_task :: custom.googleapis.com/opencensus/en-verification-server/api/issue/attempt_count | align rate() | every 1m | [resource.job]
                                            EOT
                                        }
                                    },
                                ]
                            }
                        },
                    ]
                }
              - name        = "projects/----/dashboards/54a1fab8-50ff-4a9d-9c26-a156b3d35b4f" -> null
            }
        )
        id             = "projects/-----/dashboards/54a1fab8-50ff-4a9d-9c26-a156b3d35b4f"
        project        = "encv-test"
    }
```

**Comment by yegle** [comment]
So apparently I misread the diff in `terraform plan` result and missed the bit that attempt to change `columns` field from a number `2` to a string `"2"`. In that case the diff on the `name` field and the `etag` field makes sense.

The `columns` field should always be a number, unless the concern is to support large number of columns that cannot be represented in JSON.

**Comment by guilledipa** [comment]
Folks, this is still happening. Even by fixing the `columns` field; Terraform keeps setting `name` and `etag` to `null`.

**Comment by p-le** [comment]
Stills happening, please fix.

**Comment by tpdownes** [comment]
I get similar with

```
             ~ mosaicLayout = {
                    columns = 12
                  ~ tiles   = [
...
                         + xPos   = 0
                         + yPos   = 0
...
```

**Comment by yurgas** [comment]
Got similar issue, google provider 3.82.0

```
              ~ mosaicLayout = {
                  ~ tiles   = [
                      ~ {
                          ~ widget = {
                              ~ xyChart = {
                                  ~ dataSets          = [
                                      ~ {
                                          ~ timeSeriesQuery    = {
                                              + apiSource        = "DEFAULT_CLOUD"
                                              ~ timeSeriesFilter = {
                                                  ~ aggregation          = {
                                                      + crossSeriesReducer = "REDUCE_NONE"
                                                    }
                                                  ~ secondaryAggregation = {
                                                      + perSeriesAligner   = "ALIGN_NONE"
                                                    }
                                                }
                                            }
                                        },
                                    ]
                                }
                            }
                          + yPos   = 0
                        },
```

**Comment by aprettyloner** [comment]
Can we get a timeslot for this?

I am constantly getting the same. This causes very noisy (and difficult to parse) tf plans, with 266 of these `= "Y1" -> null` across ~20 dashboards templated with .tpl. I've tried adding to the template file but still causes same plan issue:

```
            "dataSets": [
              {
                "targetAxis": null,
```


![image](https://user-images.githubusercontent.com/22802852/135496278-2cebd978-12a9-4a25-8974-e814d7a61ba7.png)

**Comment by olivertappin** [comment]
Regarding the `etag` and `name` attributes, I can definitely still see this happening:

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.google.google_monitoring_dashboard.dashboard will be updated in-place
  ~ resource "google_monitoring_dashboard" "dashboard" {
      ~ dashboard_json = jsonencode(
          ~ {
              + category     = "CUSTOM"
              - etag         = "3a478bf0ba2468b2a45370c4398ddf17" -> null
              - name         = "projects/0123456789/dashboards/4ea94d10-f379-497f-bb03-23a1a21ad653" -> null
                # (2 unchanged elements hidden)
            }
        )
        id             = "projects/0123456789/dashboards/4ea94d10-f379-497f-bb03-23a1a21ad653"
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

And that was after reviewing this thread and removing all unnecessary default items within the json. I tried adding the lifecycle block:

```
lifecycle {
  ignore_changes = [
    etag,
    name,
    dashboard_json["etag"],
    dashboard_json["name"]
  ]
}
```

but because it is json, we cannot target these items using this feature.

Please help @icco.

**Comment by davidxia** [comment]
@aprettyloner, I solved by explicitly adding all the changed fields into my TF files.

**Comment by jogoldberg** [comment]
> @aprettyloner, I solved by explicitly adding all the changed fields into my TF files.

That's a workaround, not a solution

**Comment by jogoldberg** [comment]
Confirmed the problem still exists in google 3.90.1 and google-beta 4.7.0

**Comment by ronisec** [comment]
Re @jogoldberg:

I also ended up working around this issue similarly to @davidxia. Please note that the `etag` and `name` fields don't need to be added to the JSON since they are ignored explicitly here: https://github.com/GoogleCloudPlatform/magic-modules/blob/722962c02da4972c0ae942ed57bb238e6f57277a/mmv1/third_party/terraform/resources/resource_monitoring_dashboard.go#L14.

For me the diff disappeared after removing the following from my JSON:
1. mosaicLayout>tiles>dataSets>timeSeriesQuery>timeSeriesFilter>aggregation>crossSeriesReducer = REDUCE_NONE
2. mosaicLayout>tiles>xPos = 0
3. mosaicLayout>tiles>yPos = 0
4. category = "CUSTOM"
5. mosaicLayout>tiles>dataSets>timeSeriesQuery>apiSource = "DEFAULT_CLOUD"

**Comment by tm185187** [comment]
Is there any solution for this, I still see etag keeps showing as changes in TF plan.

**Comment by enchorb** [comment]
Still an issue

**Comment by mattmclimans** [comment]
If your .JSON is static, adding the `lifecycle` meta-argument will eliminate the change outputs within your TF plan. 

```
resource "google_monitoring_dashboard" "main" {
  dashboard_json = file("my-dashboard.json.tpl")
  lifecycle {
    ignore_changes = [
      dashboard_json
    ]
  }
}
```

**Comment by tm185187** [comment]
lifecycle is not a solution, its just a bandaid and doesn't fix the root problem.

**Comment by megan07** [comment]
i believe this is fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/5595
it's as breaking change and should be in the next major release

**Comment by tm185187** [comment]
@megan07 Does that mean we can see the fix in the next google-beta version?

**Comment by megan07** [comment]
@tm185187, no sorry for the misunderstanding. The next major release will be `5.0.0`

**Comment by EricStG** [comment]
A bit late, and a bit of a hack, but we found a workaround for this

We store our dashboard definition in a file called `dashboard.json.tftpl`
We create a `random_id` resource with the hash of the dashboard as a keeper
On the `google_monitoring_dashboard`, we add `ignore_changes[dashboard_json]` to prevent change from being detected, and we include `replace_triggered_by = [random_id.dashboard.id]` to force a replacement whenever the `random_id` changes
We need the random provider here because `replace_triggered_by` requires a resource.


```terraform
locals {
  dashboard_hash = filesha256("${path.module}/dashboard.json.tftpl")
}

resource "random_id" "dashboard" {
  keepers = {
    dashboard_hash = local.dashboard_hash
  }

  byte_length = 8
}

resource "google_monitoring_dashboard" "dashboard" {
  dashboard_json = templatefile("${path.module}/dashboard.json.tftpl", {})

  lifecycle {
    replace_triggered_by = [
      random_id.dashboard.id
    ]
    ignore_changes = [
      dashboard_json
    ]
  }
}
```

**Comment by alina-bylkova** [comment]
Still facing this issue

**Comment by RezaRahmati** [comment]
> dashboard_json

what if there is a really change, by this no changes are going to be detected

**Comment by quentin-dietz** [comment]
I've found an ok workaround to "fix" this.
1. Edit your dashboard in Terraform or in the online editor
2. Navigate to https://cloud.google.com/monitoring/api/ref_v3/rest/v1/projects.dashboards/get and fill out the name parameter in "try this method", execute it.
3. Copy the resulting json in your dashboard json file.
4. your Terraform apply should no longer show modifications.

**Comment by peter-volkov** [comment]
@quentin-dietz 
```gcloud monitoring dashboards describe "projects/104463201739/dashboards/2cb93d49-4227-4b8b-81a8-ba68b68c04d8" --format=json > mydash.json```

**Comment by dbt-lucka** [comment]
Still an issue

**Comment by c2thorn** [comment]
https://github.com/GoogleCloudPlatform/magic-modules/pull/9065 should fix this, which is scheduled to be released with 5.0.0 (targeted for next week)

**Comment by IchordeDionysos** [comment]
@c2thorn We are still experiencing this:

<details><summary>Full Example reproducing the issue:</summary>
<p>

```tf
terraform {
  required_version = ">= 1.3.0, < 2.0.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

variable "project" {
  type = string
}

variable "region" {
  type = string
}

provider "google" {
  project = var.project
  region  = var.region
}

resource "google_monitoring_dashboard" "dashboard" {

  dashboard_json = <<EOF
  {
  "dashboardFilters": [],
  "displayName": "Perma diff dashboard",
  "labels": {},
  "mosaicLayout": {
    "columns": 12,
    "tiles": [
      {
        "height": 4,
        "widget": {
          "title": "SLO Compliance: 99.9% - Good/Total Ratio - Rolling 28 days",
          "xyChart": {
            "chartOptions": {
              "mode": "COLOR"
            },
            "dataSets": [
              {
                "breakdowns": [],
                "dimensions": [],
                "measures": [],
                "plotType": "LINE",
                "targetAxis": "Y1",
                "timeSeriesQuery": {
                  "timeSeriesFilter": {
                    "aggregation": {
                      "perSeriesAligner": "ALIGN_NEXT_OLDER"
                    },
                    "filter": "select_slo_compliance(\"projects/${var.project}/services/run-service/serviceLevelObjectives/run-service-rolling-availability-slo\")"
                  },
                  "unitOverride": "10^2.%"
                }
              }
            ],
            "thresholds": [
              {
                "label": "",
                "targetAxis": "Y1",
                "value": 0.999
              }
            ]
          }
        },
        "width": 12
      },
      {
        "height": 4,
        "widget": {
          "title": "SLO Compliance: 95% - 90th percentile latency under 1000ms - Rolling 28 days",
          "xyChart": {
            "chartOptions": {
              "mode": "COLOR"
            },
            "dataSets": [
              {
                "breakdowns": [],
                "dimensions": [],
                "measures": [],
                "plotType": "LINE",
                "targetAxis": "Y1",
                "timeSeriesQuery": {
                  "timeSeriesFilter": {
                    "aggregation": {
                      "perSeriesAligner": "ALIGN_NEXT_OLDER"
                    },
                    "filter": "select_slo_compliance(\"projects/${var.project}/services/run-service/serviceLevelObjectives/run-service-latency-slo\")"
                  },
                  "unitOverride": "10^2.%"
                }
              }
            ],
            "thresholds": [
              {
                "label": "",
                "targetAxis": "Y1",
                "value": 0.95
              }
            ]
          }
        },
        "width": 12,
        "yPos": 4
      },
      {
        "height": 4,
        "widget": {
          "title": "Requests per response code class",
          "xyChart": {
            "chartOptions": {
              "mode": "COLOR"
            },
            "dataSets": [
              {
                "breakdowns": [],
                "dimensions": [],
                "measures": [],
                "minAlignmentPeriod": "60s",
                "plotType": "LINE",
                "targetAxis": "Y1",
                "timeSeriesQuery": {
                  "timeSeriesFilter": {
                    "aggregation": {
                      "alignmentPeriod": "60s",
                      "perSeriesAligner": "ALIGN_RATE"
                    },
                    "filter": "metric.type=\"loadbalancing.googleapis.com/https/request_count\" resource.type=\"https_lb_rule\" (resource.label.backend_target_name=\"api-lb-backend-run-service\")",
                    "secondaryAggregation": {
                      "alignmentPeriod": "60s",
                      "crossSeriesReducer": "REDUCE_MEAN",
                      "groupByFields": [
                        "metric.label.\"response_code_class\""
                      ],
                      "perSeriesAligner": "ALIGN_MEAN"
                    }
                  }
                }
              }
            ],
            "thresholds": [],
            "timeshiftDuration": "0s",
            "yAxis": {
              "label": "y1Axis",
              "scale": "LINEAR"
            }
          }
        },
        "width": 12,
        "yPos": 8
      },
      {
        "height": 4,
        "widget": {
          "title": "Latency 50th & 95th percentile",
          "xyChart": {
            "chartOptions": {
              "mode": "COLOR"
            },
            "dataSets": [
              {
                "breakdowns": [],
                "dimensions": [],
                "measures": [],
                "minAlignmentPeriod": "60s",
                "plotType": "LINE",
                "targetAxis": "Y1",
                "timeSeriesQuery": {
                  "timeSeriesFilter": {
                    "aggregation": {
                      "alignmentPeriod": "60s",
                      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
                      "groupByFields": [],
                      "perSeriesAligner": "ALIGN_DELTA"
                    },
                    "filter": "metric.type=\"loadbalancing.googleapis.com/https/total_latencies\" resource.type=\"https_lb_rule\" (resource.label.backend_target_name=\"api-lb-backend-run-service\")"
                  }
                }
              },
              {
                "breakdowns": [],
                "dimensions": [],
                "measures": [],
                "minAlignmentPeriod": "60s",
                "plotType": "LINE",
                "targetAxis": "Y1",
                "timeSeriesQuery": {
                  "timeSeriesFilter": {
                    "aggregation": {
                      "alignmentPeriod": "60s",
                      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
                      "groupByFields": [],
                      "perSeriesAligner": "ALIGN_DELTA"
                    },
                    "filter": "metric.type=\"loadbalancing.googleapis.com/https/total_latencies\" resource.type=\"https_lb_rule\" (resource.label.backend_target_name=\"api-lb-backend-run-service\")"
                  }
                }
              }
            ],
            "thresholds": [],
            "timeshiftDuration": "0s",
            "yAxis": {
              "label": "y1Axis",
              "scale": "LINEAR"
            }
          }
        },
        "width": 12,
        "yPos": 12
      },
      {
        "height": 4,
        "widget": {
          "title": "Cache Hit Ratio",
          "xyChart": {
            "chartOptions": {
              "mode": "COLOR"
            },
            "dataSets": [
              {
                "breakdowns": [],
                "dimensions": [],
                "measures": [],
                "plotType": "LINE",
                "targetAxis": "Y1",
                "timeSeriesQuery": {
                  "timeSeriesFilterRatio": {
                    "denominator": {
                      "aggregation": {
                        "alignmentPeriod": "60s",
                        "crossSeriesReducer": "REDUCE_SUM",
                        "groupByFields": [
                          "resource.label.\"backend_target_name\""
                        ],
                        "perSeriesAligner": "ALIGN_RATE"
                      },
                      "filter": "metric.type=\"loadbalancing.googleapis.com/https/backend_request_count\" resource.type=\"https_lb_rule\" (resource.label.backend_target_name=\"api-lb-backend-run-service\")"
                    },
                    "numerator": {
                      "aggregation": {
                        "alignmentPeriod": "60s",
                        "crossSeriesReducer": "REDUCE_SUM",
                        "groupByFields": [],
                        "perSeriesAligner": "ALIGN_RATE"
                      },
                      "filter": "metric.type=\"loadbalancing.googleapis.com/https/backend_request_count\" resource.type=\"https_lb_rule\" metric.label.\"cache_result\"=\"HIT\" (resource.label.backend_target_name=\"api-lb-backend-run-service\")"
                    }
                  }
                }
              }
            ],
            "thresholds": [],
            "timeshiftDuration": "0s",
            "yAxis": {
              "label": "y1Axis",
              "scale": "LINEAR"
            }
          }
        },
        "width": 12,
        "yPos": 16
      },
      {
        "height": 7,
        "widget": {
          "logsPanel": {
            "filter": "resource.type=\"cloud_function\"\nlog_name=\"projects/${var.project}/logs/cloudaudit.googleapis.com%2Factivity\"\nprotoPayload.request.function.labels.domain=\"run-service\"",
            "resourceNames": [
              "projects/${var.project}"
            ]
          },
          "title": "API deployments"
        },
        "width": 12,
        "yPos": 20
      }
    ]
  }
}
EOF
}

```

</p>
</details> 

<details><summary>Minimal example reproducing the issue</summary>
<p>

```tf
terraform {
  required_version = ">= 1.3.0, < 2.0.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

variable "project" {
  type    = string
  default = "simpleclub-stage"
}

variable "region" {
  type    = string
  default = "europe-west1"
}

provider "google" {
  project = var.project
  region  = var.region
}

resource "google_monitoring_dashboard" "dashboard" {

  dashboard_json = <<EOF
  {
  "dashboardFilters": [],
  "displayName": "Perma diff dashboard",
  "labels": {},
  "mosaicLayout": {
    "columns": 12,
    "tiles": [
      {
        "height": 4,
        "widget": {
          "title": "SLO Compliance: 99.9% - Good/Total Ratio - Rolling 28 days",
          "xyChart": {
            "chartOptions": {
              "mode": "COLOR"
            },
            "dataSets": [
              {
                "breakdowns": [],
                "dimensions": [],
                "measures": [],
                "plotType": "LINE",
                "targetAxis": "Y1",
                "timeSeriesQuery": {
                  "timeSeriesFilter": {
                    "aggregation": {
                      "perSeriesAligner": "ALIGN_NEXT_OLDER"
                    },
                    "filter": "select_slo_compliance(\"projects/${var.project}/services/run-service/serviceLevelObjectives/run-service-rolling-availability-slo\")"
                  },
                  "unitOverride": "10^2.%"
                }
              }
            ],
            "thresholds": [
              {
                "label": "",
                "targetAxis": "Y1",
                "value": 0.999
              }
            ]
          }
        },
        "width": 12
      }
    ]
  }
}
EOF
}
```

</p>
</details> 

<details><summary>Terraform output after re-planning (with perma diffs):</summary>
<p>

```tf

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_monitoring_dashboard.dashboard will be updated in-place
  ~ resource "google_monitoring_dashboard" "dashboard" {
      ~ dashboard_json = jsonencode(
          ~ {
              + dashboardFilters = []
              - etag             = "dashboard-etag"
              + labels           = {}
              ~ mosaicLayout     = {
                  ~ tiles   = [
                      ~ {
                          ~ widget = {
                              ~ xyChart = {
                                  ~ dataSets     = [
                                      ~ {
                                          + breakdowns      = []
                                          + dimensions      = []
                                          + measures        = []
                                            # (3 unchanged attributes hidden)
                                        },
                                    ]
                                  ~ thresholds   = [
                                      ~ {
                                          + label      = ""
                                            # (2 unchanged attributes hidden)
                                        },
                                    ]
                                    # (1 unchanged attribute hidden)
                                }
                                # (1 unchanged attribute hidden)
                            }
                            # (2 unchanged attributes hidden)
                        },
                    ]
                    # (1 unchanged attribute hidden)
                }
              - name             = "projects/projectA/dashboards/dashboard-id"
                # (1 unchanged attribute hidden)
            }
        )
        id             = "projects/projectA/dashboards/dashboard-id"
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
```

</p>
</details> 

I hope this helps reproduce the issue and I hope we don't need to wait until the next major version again to get this fixed 😅 

This is a long-standing annoyance, polluting the changes when applying Terraform, leading to important differences being missed more easily.

**Comment by IchordeDionysos** [comment]
There is also a test related to perma diffs/updates that is still skipped:
https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/monitoring/resource_monitoring_dashboard_test.go#L43C10-L43C10

**Comment by IchordeDionysos** [comment]
@c2thorn I've [opened a PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/9197) for the magic-modules adding a test that triggers a failure with the latest version of the `google_monitoring_dashboard` resource.

The PR does not include any fixes yet and is opened as a draft.
I don't have any ideas at this time on how to fix it but it should help show-casing why it fails and hopefully help to fix it.

If you have any ideas how to fix it, I can maybe try to take a look.

**Comment by c2thorn** [comment]
@IchordeDionysos Thanks for your effort identifying this. Do you mind opening another issue with the same information you've already put in this thread? That would be better for our tracking. I'll take a look this week.
