### ISSUE TITLE
Issue deploying Dialogflow CX Agent in us-central1

### ISSUE THREAD

**Issue by kmorales90** [hashicorp/terraform-provider-google#9809]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.15.4

### Affected Resource(s)

* google_dialogflow_cx_agent

### Terraform Configuration Files

```tf
resource "google_dialogflow_cx_agent" "full_agent" {
  display_name = "dialogflowcx-agent"
  location = "us-central1"
  default_language_code = "en"
  supported_language_codes = ["fr","de","es"]
  time_zone = "America/New_York"
  description = "Example description."
  avatar_uri = "https://cloud.google.com/_static/images/cloud/icons/favicons/onecloud/super_cloud.png"
  enable_stackdriver_logging = true
  enable_spell_correction    = true
    speech_to_text_settings {
        enable_speech_adaptation = true
    }
}
```

### Debug Output

https://gist.github.com/kmorales90/0667343ec0ff6a7298535214f5fe202f

### Expected Behavior

Agent should be created in 'us-central1'

### Actual Behavior

 Error creating Agent: googleapi: Error 400: Please switch to 'us-central1-dialogflow.googleapis.com' to access resources located in 'us-central1'.
### Steps to Reproduce

1. `terraform apply`

### References

* Internal issue: [http://b/227464895](http://b/227464895)

**Comment by kmorales90** [comment]
It seems like the provider is not using regional endpoint

**Comment by edwardmedia** [comment]
@kmorales90 can you share your full debug log?

**Comment by jcanizalez** [comment]
hi @kmorales90 the provider is using the [documented endpoint], Is not 
a regional (https://cloud.google.com/dialogflow/cx/docs/reference/rest/v3-overview) 
![image](https://user-images.githubusercontent.com/27365102/129602549-a9b2cce1-e6a1-48b8-a0c7-0c2775729b5f.png)

Can you share your debug log?

**Comment by kmorales90** [comment]
I included debug log https://gist.github.com/kmorales90/0667343ec0ff6a7298535214f5fe202f

**Comment by kmorales90** [comment]
@jcanizalez  Maybe google updated the endpoint, because was worked fine before and now even if I use the previous google provider version I receiving the same error

**Comment by edwardmedia** [comment]
@kmorales90 can you review `Note` for the field of [location](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dialogflow_cx_agent#location) to see if that make sense?

**Comment by jcanizalez** [comment]
Hi I did a local test and like @kmorales90 mentioned is the create agent is failing when using us-central1 I opened a ticket with Google support, and see the response below:
![image](https://user-images.githubusercontent.com/27365102/129975402-27c3ac3f-b420-4e1a-b73f-31af2ebb6a8c.png)

So if you check the url https://cloud.google.com/dialogflow/cx/docs/concept/region is required to use [region-id]-dialogflow.googleapis.com in the url API endpoint. I raised a PR to fix this issue

**Comment by jcanizalez** [comment]
It seems like google updated documentation

![image](https://user-images.githubusercontent.com/27365102/131758561-9c9ec65a-2b17-4fb1-ac08-ed2b462d50a5.png)

**Comment by hege-aliz** [comment]
Hello,
I've just bumped into this issue a year later... Does this mean that with terraform we can only manage global agents at the moment?

**Comment by jcanizalez** [comment]
Hi @hege-aliz 
yeah at the moment you can only manage global agents with terraform

**Comment by jcanizalez** [comment]
hi @hege-aliz 

It seems this issue was fixed in  [v4.18.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v4.18.0)

Please check and let us know so we can request to close this issue

**Comment by hege-aliz** [comment]
hi @jcanizalez,
I can confirm, it's working with 4.18.0, thank you!

**Comment by BolajiAkerele2013** [comment]
Hello,
I was able to create the agent but I'm still unable to create google_dialogflow_cx_version resource with 4.18.0
Error message is 
"Error waiting to create Version: Error waiting for creating Version: error while retrieving operation: googleapi: Error 400: Please switch to 'us-central1-dialogflow.googleapis.com'
Any ideas please?

**Comment by BolajiAkerele2013** [comment]
> Hello, I was able to create the agent but I'm still unable to create google_dialogflow_cx_version resource with 4.18.0 Error message is "Error waiting to create Version: Error waiting for creating Version: error while retrieving operation: googleapi: Error 400: Please switch to 'us-central1-dialogflow.googleapis.com' Any ideas please?

Interestingly, when I check the dialogflow console, I notice the version gets successfully created but then Terraform still flags the error about location.

**Comment by princekalra014** [comment]
Error : Please switch to 'us-central1-dialogflow'
Solution : 
const REGION_ID=env.DIALOGFLOW.location
const credentials = {
            client_email: env.DIALOGFLOW_client_email,
            private_key: env.DIALOGFLOW_private_key
        } 
const sessionClient = new SessionsClient({
                apiEndpoint: `${REGION_ID}-dialogflow.googleapis.com`, credentials
            });

**Comment by roaks3** [comment]
It looks like this was fixed by https://github.com/GoogleCloudPlatform/magic-modules/pull/6752
